#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEMO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GAS_DIR="$DEMO_DIR/apps-script"
WORK_DIR="$DEMO_DIR/.gas-work"  # clasp 作業ディレクトリ（一時的）

echo "=== GAS Deploy Script ==="

# 1. clasp チェック
if ! command -v clasp &>/dev/null && ! $CLASP --version &>/dev/null; then
  echo "Error: clasp not found. Run: npm install -g @google/clasp"
  exit 1
fi
CLASP=$(command -v clasp || echo "$CLASP")

# 2. ログイン状態チェック
if [ ! -f "$HOME/.clasprc.json" ]; then
  echo "Error: Not logged in. Run: $CLASP login --no-localhost"
  exit 1
fi

# 3. GAS プロジェクト作成（clasp 作業ディレクトリ内）
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# .clasp.json が既にあれば削除（新規作成のため）
rm -f .clasp.json

$CLASP create --type standalone --title "Purchase Ledger Demo"
echo "GAS project created."

# 4. Code.gs + appsscript.json をコピー
cp "$GAS_DIR/Code.gs" "$WORK_DIR/"
if [ -f "$GAS_DIR/appsscript.json" ]; then
  cp "$GAS_DIR/appsscript.json" "$WORK_DIR/"
else
  cat > "$WORK_DIR/appsscript.json" <<'MANIFEST'
{
  "timeZone": "Asia/Tokyo",
  "dependencies": {},
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8",
  "webapp": {
    "access": "ANYONE_ANONYMOUS",
    "executeAs": "USER_DEPLOYING"
  }
}
MANIFEST
fi

# 5. clasp push
$CLASP push --force
echo "Code pushed."

# 6. clasp deploy（Web App）
DEPLOY_OUTPUT=$($CLASP deploy --description "E2E auto-deploy")
echo "Deploy output: $DEPLOY_OUTPUT"

# clasp deploy の出力からデプロイ ID を抽出
# 典型的な出力: "Created version 1." + "- <deploymentId> @1."
DEPLOY_ID=$(echo "$DEPLOY_OUTPUT" | grep -oE 'AKfycb[A-Za-z0-9_-]+' || echo "")

if [ -z "$DEPLOY_ID" ]; then
  echo "Warning: Could not parse deploy ID from output."
  echo "Attempting to list deployments..."
  DEPLOY_LIST=$($CLASP deployments)
  echo "$DEPLOY_LIST"
  DEPLOY_ID=$(echo "$DEPLOY_LIST" | grep -oE 'AKfycb[A-Za-z0-9_-]+' | tail -1 || echo "")
fi

if [ -z "$DEPLOY_ID" ]; then
  echo "Error: Failed to get deployment ID."
  exit 1
fi

# Script ID を .clasp.json から取得
SCRIPT_ID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$WORK_DIR/.clasp.json','utf8')).scriptId)")
WEB_APP_URL="https://script.google.com/macros/s/${DEPLOY_ID}/exec"

echo "Deploy ID: $DEPLOY_ID"
echo "Script ID: $SCRIPT_ID"
echo "Web App URL: $WEB_APP_URL"

# 7. Script Properties 設定
SELF_GENERATED_TOKEN=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
ADMIN_PASSCODE=$(node -e "console.log(require('crypto').randomBytes(12).toString('base64url'))")
echo "Generated Self-Generated Token: $SELF_GENERATED_TOKEN"
echo "Generated Admin Passcode: $ADMIN_PASSCODE"
echo ""
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo " IMPORTANT: Save these credentials now."
echo " - SELF_GENERATED_TOKEN is required for Connection Settings in demo/admin."
echo " - ADMIN_PASSCODE is required to unlock demo/admin."
echo "SELF_GENERATED_TOKEN=$SELF_GENERATED_TOKEN"
echo "ADMIN_PASSCODE=$ADMIN_PASSCODE"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo ""

# 一時関数で Script Properties を設定
cat > "$WORK_DIR/SetProperties.gs" <<PROPS
function setScriptProperties_() {
  var props = PropertiesService.getScriptProperties();
  props.setProperties({
    'SELF_GENERATED_TOKEN': '${SELF_GENERATED_TOKEN}',
    'ADMIN_PASSCODE': '${ADMIN_PASSCODE}'
  });
  return 'Properties set successfully';
}
PROPS

$CLASP push --force
$CLASP run setScriptProperties_ 2>/dev/null || echo "Warning: clasp run failed (manual properties setup may be needed)"

# 元の Code.gs に戻す（SetProperties.gs を削除）
rm -f "$WORK_DIR/SetProperties.gs"
$CLASP push --force

# 8. .env 出力
cat > "$DEMO_DIR/.env" <<ENV
# Auto-generated by deploy-gas.sh
GAS_ENDPOINT_URL=$WEB_APP_URL
GAS_SELF_GENERATED_TOKEN=$SELF_GENERATED_TOKEN
GAS_ADMIN_PASSCODE=$ADMIN_PASSCODE
ENV

echo ""
echo "=== Deploy Complete ==="
echo ".env written to: $DEMO_DIR/.env"
echo "Use these in the admin screen (demo/admin):"
echo "Self-Generated Token: $SELF_GENERATED_TOKEN"
echo "Admin Passcode: $ADMIN_PASSCODE"
