#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEMO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GAS_DIR="$DEMO_DIR/apps-script"
WORK_DIR="$DEMO_DIR/.gas-work"  # clasp 作業ディレクトリ（一時的）

echo "=== GAS Deploy Script ==="

# 1. clasp チェック
if ! npx clasp --version &>/dev/null; then
  echo "Error: clasp not found. Run: npm install -g @google/clasp"
  exit 1
fi

# 2. ログイン状態チェック
if [ ! -f "$HOME/.clasprc.json" ]; then
  echo "Error: Not logged in. Run: npx clasp login --no-localhost"
  exit 1
fi

# 3. スプレッドシート作成
echo "Creating spreadsheet..."
SHEET_ID=$(node "$SCRIPT_DIR/setup-gas-project.js" create-sheet)
echo "Spreadsheet ID: $SHEET_ID"

# 4. GAS プロジェクト作成（clasp 作業ディレクトリ内）
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# .clasp.json が既にあれば削除（新規作成のため）
rm -f .clasp.json

npx clasp create --type sheets --parentId "$SHEET_ID" --title "買取台帳 E2E"
echo "GAS project created."

# 5. Code.gs + appsscript.json をコピー
cp "$GAS_DIR/Code.gs" "$WORK_DIR/"
if [ -f "$GAS_DIR/appsscript.json" ]; then
  cp "$GAS_DIR/appsscript.json" "$WORK_DIR/"
else
  cat > "$WORK_DIR/appsscript.json" <<'MANIFEST'
{
  "timeZone": "Asia/Tokyo",
  "dependencies": {},
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8",
  "webapp": {
    "access": "ANYONE_ANONYMOUS",
    "executeAs": "USER_DEPLOYING"
  }
}
MANIFEST
fi

# 6. clasp push
npx clasp push --force
echo "Code pushed."

# 7. clasp deploy（Web App）
DEPLOY_OUTPUT=$(npx clasp deploy --description "E2E auto-deploy")
echo "Deploy output: $DEPLOY_OUTPUT"

# clasp deploy の出力からデプロイ ID を抽出
# 典型的な出力: "Created version 1." + "- <deploymentId> @1."
DEPLOY_ID=$(echo "$DEPLOY_OUTPUT" | grep -oE 'AKfycb[A-Za-z0-9_-]+' || echo "")

if [ -z "$DEPLOY_ID" ]; then
  echo "Warning: Could not parse deploy ID from output."
  echo "Attempting to list deployments..."
  DEPLOY_LIST=$(npx clasp deployments)
  echo "$DEPLOY_LIST"
  DEPLOY_ID=$(echo "$DEPLOY_LIST" | grep -oE 'AKfycb[A-Za-z0-9_-]+' | tail -1 || echo "")
fi

if [ -z "$DEPLOY_ID" ]; then
  echo "Error: Failed to get deployment ID."
  exit 1
fi

# Script ID を .clasp.json から取得
SCRIPT_ID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$WORK_DIR/.clasp.json','utf8')).scriptId)")
WEB_APP_URL="https://script.google.com/macros/s/${DEPLOY_ID}/exec"

echo "Deploy ID: $DEPLOY_ID"
echo "Script ID: $SCRIPT_ID"
echo "Web App URL: $WEB_APP_URL"

# 8. Script Properties 設定
API_KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
echo "Generated API Key: $API_KEY"

# 一時関数で Script Properties を設定
cat > "$WORK_DIR/SetProperties.gs" <<PROPS
function setScriptProperties_() {
  var props = PropertiesService.getScriptProperties();
  props.setProperties({
    'API_KEY': '${API_KEY}',
    'SHEET_ID': '${SHEET_ID}',
    'SHEET_NAME': 'Sheet1'
  });
  return 'Properties set successfully';
}
PROPS

npx clasp push --force
npx clasp run setScriptProperties_ 2>/dev/null || echo "Warning: clasp run failed (manual properties setup may be needed)"

# 元の Code.gs に戻す（SetProperties.gs を削除）
rm -f "$WORK_DIR/SetProperties.gs"
npx clasp push --force

# 9. .env 出力
cat > "$DEMO_DIR/.env" <<ENV
# Auto-generated by deploy-gas.sh
GAS_ENDPOINT_URL=$WEB_APP_URL
GAS_API_KEY=$API_KEY
GOOGLE_SHEET_ID=$SHEET_ID
ENV

echo ""
echo "=== Deploy Complete ==="
echo ".env written to: $DEMO_DIR/.env"
echo "Spreadsheet: https://docs.google.com/spreadsheets/d/$SHEET_ID"
